// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

const createTransactionAssets = `-- name: CreateTransactionAssets :batchexec
INSERT INTO transaction_asset (transaction_id, asset_id, quantity) VALUES ($1, $2, $3)
`

type CreateTransactionAssetsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateTransactionAssetsParams struct {
	TransactionID int64 `json:"transaction_id"`
	AssetID       int64 `json:"asset_id"`
	Quantity      int64 `json:"quantity"`
}

func (q *Queries) CreateTransactionAssets(ctx context.Context, arg []CreateTransactionAssetsParams) *CreateTransactionAssetsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.TransactionID,
			a.AssetID,
			a.Quantity,
		}
		batch.Queue(createTransactionAssets, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateTransactionAssetsBatchResults{br, len(arg), false}
}

func (b *CreateTransactionAssetsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, errors.New("batch already closed"))
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateTransactionAssetsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
